### ISSUE TITLE
global notice alert box with modifiable text that can be turned on or off

### ISSUE THREAD

**Issue by thatVargas** [CSPS-EFPC-IT/craft-gcweb#22]
Having a global notice alert box with modifiable text that can be turned on or off (change it once, it appears on all pages). 

Admin/publisher permissions to edit and turn on and off.

This could be done as part of the global header

**Comment by FrancisMawn** [comment]
Alvaro, I'm gonna close this one as it can be achieved with the global header functionality that is currently being added.

**Comment by thatVargas** [comment]
Sure thing. Thank you for letting me know.
