### ISSUE TITLE
Metadata tab cleanup

### ISSUE THREAD

**Issue by thatVargas** [CSPS-EFPC-IT/craft-gcweb#23]
Having the ability to enter meta data into the backend of the page, so that it will appear appropriately in the page code (head section). A few minor tweaks to come from Michael to order, etc.

**Comment by FrancisMawn** [comment]
The metadata fields are already in place but Michael asked for some modifications. 

1. Add two new fields:
- dcterms.issued
- dcterms.modified

These dates should be automatically populated by the system, but we need to be able to overwrite them. The modified date should be the same printed in the bottom of the page. 

2. Remove field:
- Identifier

3. Have the fields in their own separate ''Metadata" tab.  

4. Re-order the fields like so:
- Keywords
- Description
- Creator
- Subject
- Issued
- Modified
- Type
- Spatial
- Publisher
