### ISSUE TITLE
Custom HEAD information to include custom CSS on a page

### ISSUE THREAD

**Issue by thatVargas** [CSPS-EFPC-IT/craft-gcweb#24]
Ability to add custom HEAD information to include custom CSS on a page.

This would be on a tab. Maybe the page info tab with the page owner, etc. OR put in with metadata and change tab name to HEAD. Look at how we have it in the globals.

**Comment by FrancisMawn** [comment]
I was discussing that with Julien and we will add a "Customizations" tab which will include a way to add CSS and Javascript on each page.
