### ISSUE TITLE
Calendar page as is on the live site currently. 

### ISSUE THREAD

**Issue by thatVargas** [CSPS-EFPC-IT/craft-gcweb#25]
(https://www.csps-efpc.gc.ca/calendar/index-eng.aspx) I think this is done. We just need to redirect the data pull.

>We will need to confirm where the data comes from to make sure that this is appropriately executed on

**Comment by FrancisMawn** [comment]
Should this be part of the Craft GCweb baseline though? I thought it would be an internet website specific feature?

**Comment by thatVargas** [comment]
You’re right. I didn’t know that this was agnostic of sites. I’ll leave to you guys to decide. It’s one of the things that needs to get done before we launch though.

**Comment by FrancisMawn** [comment]
I'm closing this as the issue is not a Craft GCweb specific one and would need to be addressed in the internet website project.
