### ISSUE TITLE
Add page information tab.

### ISSUE THREAD

**Issue by FrancisMawn** [CSPS-EFPC-IT/craft-gcweb#28]
Add a page information tab as the first tab (before the content tab).

This tab should contain the following fields:
- Publishing Notes
- Owner
- Contributor

**Comment by jlcharette** [comment]
@FrancisMawn do we know if the Owner and Contributor are part of the system? If yes, the user entry field would probably be better than a simple textbox. As for the publishing notes, the workflow plugin already handle this, so should we add it anyway?
