### ISSUE TITLE
Add a way to preview the global features block.

### ISSUE THREAD

**Issue by FrancisMawn** [CSPS-EFPC-IT/craft-gcweb#4]
- Create a new channel for global features (this way we can preview them). 
- Prevent this channel to be indexed by bots.
- Create global settings to add header and footer entries to be displayed on all pages.
- Create a setting to show/hide the global header and footer on pages.

**Comment by jlcharette** [comment]
We need to test if it is possible to preview a channel/structure with no URL. If possible, we can create a channel named Features and pull those features in the entry default template.

**Comment by FrancisMawn** [comment]
Tested and it seems we need a URL in order to preview the entry.

**Comment by FrancisMawn** [comment]
Also, the client has indicated that their would also be a need for a global header block.

**Comment by jlcharette** [comment]
@FrancisMawn what if we still used the channel (with url) and simply prevent robots from indexing this channel? Users could preview the features section just like they would preview a page builder page?
